### ISSUE TITLE
[NHÓM#02] - Lỗi phi chức năng - Lỗi bảo mật - Ybox.vn

### ISSUE THREAD

**Issue by huythac** [UEHMonQAQC/24_901#363]
Mô tả:
a. Web Browser: 
b. Các bước phát hiện lỗi:
i. Sử dụng phần mềm Burp Suite, bật vào Proxy, chọn Open browser. Sau khi mở Browser ảo của Burp Suite thì nhập vào url:
https://ybox.vn/authentication/sign-in
ii. Khi truy cập trang web, Burp Suite sẽ dừng lại để chúng ta bấm Forward
![fcd42e06-f851-40da-abea-b66202146a4b](https://github.com/user-attachments/assets/69369e4b-2eca-499c-a69b-1d7d384f7efd)
iii.Sau khi vào trang đăng nhập, ta tiến hành đăng nhập thông tin:
nhập password: abcdef
![390a41fa-5b2f-4d9c-9790-50d3263144d2](https://github.com/user-attachments/assets/4cfada03-fa5a-4d03-a1ec-511f51848daf)
iv.Burp Suite sẽ Listen sự kiện đăng nhập và bắt sự kiện
![4b46dc44-b1fa-411c-b6a4-09cf7071a6d9](https://github.com/user-attachments/assets/508f9d4c-8e06-454b-890c-69d834c750f6)
Nhấn vào Send to Intruder. Sau đó qua tab Intruder
Giao diện Intruder: 
![69577e3c-23bf-4012-9e0b-3b5c75d5ba1a](https://github.com/user-attachments/assets/2bef354a-6663-409f-83bd-fb58799365cf)
v. Ta bôi đen vào phần password và chuột phải vào nó sau đó chọn Add payload position:
![76e8f68f-d0b2-4503-809a-65cdf4cbb383](https://github.com/user-attachments/assets/f7793eda-ae03-4ae9-afc4-58c2f5183977)
vi.Ta chọn:
Payload Type: Brute Forcer (Quét hết mọi trường hợp)
Character Set: 123 
Min-Length và MaxLength: 6 
Sau đó bấm “Start Attack”:
![40de2817-34b0-4efd-9921-d17ebe18869d](https://github.com/user-attachments/assets/f5ec5006-06ea-4f55-a976-0a58d3c03351)
Kiểm tra các response, thu được kết quả với passoword 111111 trả response là người dùng
![Uploading d3a5664c-c186-4098-8e1b-5e0b63873496.jpg…]()

Kết Quả mong muốn: Mật khẩu được bảo mật và được giới hạn lượt nhập.
Kết quả thực tế: Mật khẩu dễ dàng bị Burp Suite Brute Force tìm ra mật khẩu.

**Comment by 31221025597** [comment]
Không up nữa nha. Không tính từ T2 tuần này nữa rồi

Vào Th 4, 11 thg 12, 2024 lúc 14:48 huythac ***@***.***> đã
viết:

**Comment by 31221025597** [comment]
Không up nữa vì up cũng không tính đâu. Từ T2 tuần này đã là không tính rồi
